apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'metricas-autores'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['autores:8080']

      - job_name: 'metricas-libros'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['libros:8080']

      - job_name: 'metricas-prometheus'
        static_configs:
          - targets: ['prometheus-metricas:9090']

      - job_name: 'metricas-traefik-proxy'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['traefik-proxy:8082']

      - job_name: 'metricas-postgres'
        static_configs:
          - targets: ['metricas-base-datos:9187']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-metricas
  labels:
    app: prometheus-metricas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-metricas
  template:
    metadata:
      labels:
        app: prometheus-metricas
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metricas
spec:
  selector:
    app: prometheus-metricas
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
